### PR TITLE
#32 fix the bug  If multiple rows of data contain UTF8 character

### PR DESCRIPTION
**Pull request by haptear**

### CODE REVIEW

**Comment by minhhungit** [comment]
Can you please check why these rows are skewed

image

**Comment by haptear** [comment]
@minhhungit 
Because there are UTF8 characters, the output of Console is correct

image

**Comment by minhhungit** [comment]
I actually also worry about the problem when user just want to show table as text, for example they put the table into an email.
Is there a way we can handle both cases @haptear 

Anyway, thanks for the PR

**Comment by minhhungit** [comment]
Do you think we should have a toogle to turn on/off it

**Comment by haptear** [comment]
yes a toogle  switch to print to console  or print to file

**Comment by minhhungit** [comment]
@haptear it will be great if you can implement that feature please, I will merge this PR after that. 

I'm sorry I'm quite busy these days so I greatly appreciate your help. Many thanks

**Comment by haptear** [comment]
@minhhungit  ok i will finish the feature

**Comment by haptear** [comment]
@minhhungit  
I have tested the whole thing and it's not a code problem, it's a font selection problem.
If you set a monospaced font, the display format is correct.
not monospaced font UTF8 character and Uppercase character will cause the display format is not correct.

font with 'Arial' 
image

font with 'Consolas' the monospaced font
image

font with 'Arial' have Uppercase character
image

font with 'Consolas' have Uppercase character
image

**Comment by haptear** [comment]
My VS environment font is not set to 'Consolas', the format is correct;
image

**Comment by minhhungit** [comment]
So do we still need a toggle to turn on/off utf8/unicode mode @haptear ?

**Comment by haptear** [comment]
Not anymore

If anyone need to send emails, please use the HTML template to send.
The formatting is correct, because HTML is monospaced font by default.

**Comment by minhhungit** [comment]
thanks @haptear

**Pull request merged**
